name: graphis
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  - conda-forge::numpy>=1.24.2
  - conda-forge::Pillow>=9.4.0
  - conda-forge::PySide2>=5.15.8
  - conda-forge::Shapely>=2.0.1
  - pip
  - pip:
        - PyExifTool>=0.5.5
        - rawpy>=0.18.0